### PR TITLE
replace spop library

### PR DESCRIPTION
**Pull request by fionera**
As discussed in #51 this can be used as replacement for the current spop library. I didnt make the code any more fancy, just replaced it quick and dirty

### CODE REVIEW

**Comment by fzipi** [comment]
Hi @fionera. Thanks for your contribution.

While looking at the code, you have added your own package here. Sadly, there is no license in the code you published. Can you clarify that, please?

**Comment by fionera** [comment]
Oops yes, let me push a license real quick

**Comment by fionera** [comment]
Just pushed the LICENSE file. Everything in that repo is licensed under Apache-2.0 :)

**Comment by fionera** [comment]
Just updated the PR to the current version which contains lots of fixed :)

**Comment by fionera** [comment]
Will be replaced by another PR

**Pull request closed without merging**
