### PR TITLE
Introduce "default_application" concept

### PR DESCRIPTION
**Pull request by NullIsNot0**
This PR contains the same changes as #36. It was easier for me to create new PR than change branch to main and manually solve merge conflicts if there are any.

### CODE REVIEW

**Comment by NullIsNot0** [comment]
@jcchavezs, @mac-chaffee Does this PR needs more work to do?

**Comment by mac-chaffee** [comment]
I say no, let's ship it! I've been running the code in this PR for about a month now since it's required for multi-host setups.

@jcchavezs mentioned wanting tests, but I'd say a test harness should be added in a separate PR. You kinda can't even properly test this repo due to the SPOA library we're using lacking interfaces/public APIs (see #51 ), so getting to the point where we can add tests is out of scope of this PR IMO

**Comment by NullIsNot0** [comment]
@jcchavezs, would you mind merging this PR?

**Comment by jptosso** [comment]
Please fallback `transaction_ttl: 60`, as it might prevent transactions from being cleared

**Comment by NullIsNot0** [comment]
Reverted back to 60 as @sts committed on #50, but later on Slack I saw him recommending to set it to 60000 if you want 60s. (https://owasp.slack.com/archives/C02BXH135AT/p1672732670918819?thread_ts=1672660797.495589&cid=C02BXH135AT)
I think this setting needs to be investigated and fixed (if need) in another PR.

**Comment by NullIsNot0** [comment]
Cache TTL definately need to be tested. I found out that in one place it is in seconds, but in another in milliseconds.

Duration is in seconds:
https://github.com/corazawaf/coraza-spoa/blob/219d92b4838ab752e872faef3052497ee802ab89/internal/spoa.go#L223

Duration is in milliseconds:
https://github.com/corazawaf/coraza-spoa/blob/219d92b4838ab752e872faef3052497ee802ab89/internal/request.go#L57

After this PR gets merged, I'll do tests on TTL and make a PR if it needs to be fixed.

**Comment by NullIsNot0** [comment]
Ok, I changed cache duration from milliseconds to seconds in request file. Now when you set `transaction_ttl: 60` it means 60 seconds not 60 milliseconds for cache timeout.

**Comment by jcchavezs** [comment]
I still think the name `transaction_ttl` is confusing and we should use `transaction_ttl_secs` or `transaction_ttl_ms`, whatever makes sense.

**Comment by NullIsNot0** [comment]
Ok, I set it to `transaction_ttl_seconds` to be more self-explanatory.

**Comment by NullIsNot0** [comment]
Changed param name to `transaction_ttl_ms` and units in milliseconds for project to cover more use cases

**Comment by NullIsNot0** [comment]
@jptosso, @jcchavezs do I need to make additional changes in this PR for it to be accepted?

**Comment by jcchavezs** [comment]
Thanks @NullIsNot0

**Pull request merged**
