### PR TITLE
upgrade coraza to v3.0.3

### PR DESCRIPTION
**Pull request by jptosso**

### CODE REVIEW

**Comment by jcchavezs** [comment]
@M4tteoP e2e seems stuck here. Could you please migrate to new e2e?

**Comment by M4tteoP** [comment]
Tried to give it a go here: https://github.com/corazawaf/coraza-spoa/pull/85. Still a WIP, it is currently failing.
What I notice is that the e2e test started failing from the latest [commit](https://github.com/corazawaf/coraza-spoa/pull/72/commits/648db115f8ddb7a201a9763c014c3c8100776040) of https://github.com/corazawaf/coraza-spoa/pull/72, but I can't find anything obvious that originated this problem. cc @sts

**Comment by zc-devs** [comment]
Perhaps, it's because of [no_response_check: true](https://github.com/corazawaf/coraza-spoa/blob/6a0d9a3ba67379892eafa105c636d85016f8ef21/config.yaml.default#L22). If yes, you can pick up fixes from [here](https://gitea.smthd.com/mirko/coraza-spoa/commits/branch/main).

**Comment by jcchavezs** [comment]
Up for a PR?

**Comment by zc-devs** [comment]
> Up for a PR?

Unfortunately, no. I'm quite busy now.

**Comment by fzipi** [comment]
@zc-devs Do you think it is a better time now to provide a PR?

**Comment by zc-devs** [comment]
Sorry, I've changed my mind towards Kubernetes. I'm running `CrowdSec` now and probably will deploy `open-appsec`. So, I've been not using Coraza SPOA since then.

Anyway, it should be [this commit](https://gitea.smthd.com/mirko/coraza-spoa/commit/515ccd696db679e9777a15cbe9b34b9912ea23a7). Or just revert [this setting](https://github.com/corazawaf/coraza-spoa/blob/6a0d9a3ba67379892eafa105c636d85016f8ef21/config.yaml.default#L22).

**Pull request closed without merging**
