### PR TITLE
Add docker container

### PR DESCRIPTION
**Pull request by sts**
- Add Docker build for a coraza-spoa container

- Adds a mockserv which prints out request and responses in http/1
  wire format

- Add required configuration to run coraza-spoa with CRS in
  blocking mode alongside haproxy and mockserv.

To use:

  docker-compose build . && docker-compose up
  curl http://localhost:4000\?x\=/etc/passwd
  curl https://localhost:4443\?x\=/etc/passwd

### CODE REVIEW

**Comment by jptosso** [comment]
I have upgraded https://tosso.io/ to test your work. My only changes:

coraza-spoa:
```
FROM golang:1.18-alpine
RUN apk add git
RUN git clone https://github.com/corazawaf/coraza-spoa /coraza-spoa
WORKDIR /coraza-spoa
RUN go get -v ./...
RUN go build -v -o coraza-spoa cmd/main.go
RUN mv ./coraza-spoa /usr/local/bin/coraza-spoa
RUN mkdir /etc/coraza-spoa
RUN cp ./config.yaml.default /etc/coraza-spoa/config.yaml
ENTRYPOINT ["/usr/local/bin/coraza-spoa", "-config-file", "/etc/coraza-spoa/config.yaml"]
```

And I use Caddy in front of haproxy for TLS

**Review by bxlxx — APPROVED** [review]
LGTM, thank you so much

**Comment by mac-chaffee** [comment]
Was there meant to be a Dockerfile included in this PR? `docker-compose build` errors out because it expects a Dockerfile in the root of the repo.

**Comment by mac-chaffee** [comment]
Oh never mind, I see the Dockerfile exists on the experimental branch: https://github.com/corazawaf/coraza-spoa/pull/34

**Pull request merged**
